### ISSUE TITLE
v3.0.1 doesn't have cache.GetOrSet method while it's documented in README.md of master branch

### ISSUE THREAD

**Issue by mih-kopylov** [jellydator/ttlcache#104]
See 
https://github.com/jellydator/ttlcache/blob/v3.0.1/cache.go
https://github.com/jellydator/ttlcache/blob/master/README.md

Please consider either changing default branch to `v3` or make sure README.md in `master` has relevant documentation.

**Comment by Bijan-Massoumi** [comment]
BUMP

**Comment by mmnavarr** [comment]
bump

**Comment by davseby** [comment]
Everything is correct. To find v3.0.1 documentation you should be looking at [this](https://github.com/jellydator/ttlcache/tree/v3.0.1) README instead. If you want to use the `GetOrSet` method before the v3.1.0 release, you can upgrade the package to the latest non-released version via `go get github.com/jellydator/ttlcache/v3@master`.

**Comment by swithek** [comment]
The default branch is now `v3`.
