### ISSUE TITLE
Question: about memory exceeding the limit

### ISSUE THREAD

**Issue by BaiZe1998** [jellydator/ttlcache#110]
desc：If a large object remains in memory after a set, does it cause the set memory limit to be exceeded all the time. Is it better to eliminate it by for loop?

https://github.com/jellydator/ttlcache/blob/v3/cache.go#L148

```
if c.options.capacity != 0 && uint64(len(c.items.values)) >= c.options.capacity {
    // delete the oldest item
    c.evict(EvictionReasonCapacityReached, c.items.lru.Back())
}
```

**Comment by swithek** [comment]
Can you explain what you're trying to achieve? An example would help too.
