### ISSUE TITLE
Documentation Q on Get() / isExpired()

### ISSUE THREAD

**Issue by frankjkelly** [jellydator/ttlcache#140]
It appears that when calling `Get` we must check `isExpired()` is that right?

e.g.

```
	cache := ttlcache.New[string, string](
		ttlcache.WithTTL[string, string](c.CacheExpiry),
		ttlcache.WithDisableTouchOnHit[string, string](), //Do not reset the timer if there is a cache hit
	)
	go cache.Start()
.
.
.
	if cacheHas(completeCallsModeKey) {
		entry := cacheHas.Get(completeCallsModeKey)
		if !entry.IsExpired() {
			return entry.Value(), nil
		} else {
			cacheHas.DeleteExpired()
		}
	}
```

**Comment by swithek** [comment]
Hi. An item's expiration is checked before the [value is returned](https://github.com/jellydator/ttlcache/blob/v3/cache.go#L186). `IsExpired()` can be used if you plan to save an item's reference somewhere outside of the cache instance.

**Comment by frankjkelly** [comment]
@swithek Thanks - to clarify further is `includeExpired` param set to `true` or `false` by default for the `Get()` method

It appears to be `false` but just confirming https://github.com/jellydator/ttlcache/blob/62c37338e6b2e3d60cd8270834ecc15c1f8c6aff/cache.go#L221

**Comment by swithek** [comment]
You're right, it's automatically set to false in Get.
