### ISSUE TITLE
How to check if record expired or just absent

### ISSUE THREAD

**Issue by sergiizemlianyi-bc** [jellydator/ttlcache#141]
How do I check if record I set with ttl 5s is deleted because of expiration or it was not even available?

```
	lkp.cache.Set(inpKey, inpRecord, 5*time.Second)
	n := 10
	for {
		fmt.Printf("IsExpired: %+v\n", lkp.cache.Get(inpKey).IsExpired())
		time.Sleep(1 * time.Second)
		n--
		if n == 0 {
			break
		}
	}
```

it prints

```
IsExpired: false
IsExpired: false
IsExpired: false
IsExpired: false
IsExpired: false
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```

where I can check for nil of course, but is where a way to know record was deleted due to expiration?

Thanks

**Comment by swithek** [comment]
[OnEviction()](https://pkg.go.dev/github.com/jellydator/ttlcache/v3#Cache.OnEviction) is probably what you are looking for. You can check the eviction reason inside the callback.
