### ISSUE TITLE
Item.Value() is panicking (apparently trying to get lock)

### ISSUE THREAD

**Issue by RonyHor** [jellydator/ttlcache#142]
Sometimes I get panic when asking for item.Value(). I am running in a MTH environment

I am running version 3.2.0
Create cache:
type MyCachedInfo struct {
    httpClient *http.Client
    url               string
    id                string
}
cache := ttlcache.New[string, MyCachedInfo](
	ttlcache.WithTTL[string, MyCachedInfo](30 * time.Minute),
	ttlcache.WithCapacity[string, MyCachedInfo](500))
	
Read and panic:
if cache.Has("someKey") {
       item := cache.Get("someKey")
       myInfo := item.Value()        <===== panic
       
2024/07/30 11:28:53 [Recovery] 2024/07/30 - 11:28:53 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x455637)
/usr/local/go/src/runtime/signal_unix.go:881 (0x455605)
/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.2.0/item.go:131 (0x1611eb5)

**Comment by davseby** [comment]
You should check if it's not nil. There is a race condition in your code between `Has` and `Get`. Check the documentation:

```
// Get retrieves an item from the cache by the provided key.
// Unless this is disabled, it also extends/touches an item's
// expiration timestamp on successful retrieval.
// If the item is not found, a nil value is returned.
```

**Comment by RonyHor** [comment]
Thanks, I have fixed the code and check for item != nil.
Still would like to take your attention that the stack indicates code inside the item.go, line 131:
.
If the stack is correct, it is improbable that item is nil in this case.
In my case there are no deletions from the cache when this happens.

**Comment by davseby** [comment]
According to your example, a TTL is used. Could it be that the TTL was exceeded? Expired items are not returned. In any case, if you must retrieve the item the best course of action would be to skip `Has` check altogether.

```go
if item := cache.Get("someKey"); item != nil {
    myInfo := item.Value()
}
```

**Comment by gkuchta** [comment]
I also ran into this nil pointer dereference landmine. I think that there's a bit of an impedance mismatch between `Has()` and `Get()` when TTLs are involved. `Has()` will tell you that a key exists, but it doesn't _really_ exist in the context of `Get()` if the TTL's expired. I can understand why this might be the behavior you want, but it's non-obvious in the context of other general-purpose k/v stores, or in the context of the example which would imply it's a general-purpose "exists". 

I think it might be worth updating the comments on `Has()` to mention that it should not be used to determine if the cache contains a get-able key if items have a ttl attached -- which would, i think, be the general case considering the name of the package.

**Comment by swithek** [comment]
I think this problem with `Has()` would exist regardless of whether TTL were used or not (e.g., external deletion of items, especially when performed in a different goroutine, would cause this as well). It's just the way this method works -- it's not connected to the `Get()` or `Set()` in any way.

The best way to check whether an item really exists before using it is to check its nil-ness after calling `Get()`. I can think of a few use cases of `Has()`, but they aren't something most users will probably want to have. So if this method is confusing users, then maybe it would be a good idea to just deprecate and remove it in the next major release. And of course we could add an indication of some kind that would explain that `Get()` can be used the same way.

**Comment by gkuchta** [comment]
That makes sense. My immediate thought was to modify `Has()` to mirror `Get()`'s behavior with respect to an element having been TTL'd, then move the "does this key exist irrespective of it having TTL'd" behavior to a new `Exists()` method. That said, I know that changing API surfaces can be tricky and I didn't want to shore up in your repos with a "well *I* think it should work like this" hottake PR 😆 I think a comment would be totally sufficient, but depreciation in favor of checking `if item := ttlcache.Get(key); item != nil {` probably introduces the least potential for confusion. Thanks for thinking about this!
