### ISSUE TITLE
`Has` method includes expired keys

### ISSUE THREAD

**Issue by hongkuancn** [jellydator/ttlcache#147]
I noticed the `Has` method will print `true` when checking an expired key
```go
func Test_Has(t *testing.T) {
	cache := New[int, int]()
	cache.Set(1, 1, time.Nanosecond)
	time.Sleep(time.Second)
	fmt.Println(cache.Has(1))
}
```
output:
```
true
```
I think it makes more sense to exclude expired keys here and it won't cause much overhead just to check if the item expires. If so, I have some time to make the change.

**Comment by swithek** [comment]
I believe most data/status retrieval methods include expired keys (i.e., `Len()`, `Keys()`, `Range()`, `Has()`), so we should probably update all of them. Using `item.isExpiredUnsafe()` in them, just like you did in your latest PR, should be enough.

If you can tackle this issue, feel free to do that, I'll review your PRs ASAP.
