### ISSUE TITLE
go1.18 and generics

### ISSUE THREAD

**Issue by swithek** [jellydator/ttlcache#63]
Are there any plans to upgrade the project to go1.18 (when it's released) and replace `interface{}` types with generic types? 

I can open a draft PR with changes made using gotip in the near future if this is something you'd be interested in @ReneKroon.

**Comment by ReneKroon** [comment]
I'm very much expecting to do that, that would become new major version 3. However i won't be ahead of schedule so if you can create something like this it would be great.

**Comment by ReneKroon** [comment]
Available as version 3.0.0-beta until go 1.18 will be released

**Comment by swithek** [comment]
The v3 has been [released](https://github.com/jellydator/ttlcache/releases/tag/v3.0.0).
