### ISSUE TITLE
Upgrade to v3

### ISSUE THREAD

**Issue by swithek** [jellydator/ttlcache#68]
Before the stable release of v3, some additional, non-backwards compatible changes could be made. Here is a list of my proposed changes:
- [x] Update README.md
- [x] Allow [TTL extension](https://github.com/ReneKroon/ttlcache/blob/master/cache.go#L524) to be enabled/disabled per Get() call, rather than per cache instance. Having them both could also work: the global cache value would be used as the default one. 
- [x] Use functional options to set cache options.
- [x] Remove the [SimpleCache](https://github.com/ReneKroon/ttlcache/blob/master/cache.go#L24) interface, since it serves no purpose, at least in this package. The [idiomatic approach](https://github.com/golang/go/wiki/CodeReviewComments#interfaces) is to allow the client/user of the package to create their own interface, with their own limited set of methods. However, if there are clear and useful examples of where this is may be needed, this interface should be at least renamed to something more appropriate.
- [x] Rename the event methods and make them follow `On[Noun](fn)` naming pattern (e.g. `OnExpiration(fn)`). The provided functions should also be stored in a slice rather than a simple field. A good example of this is [bolt's OnCommit](https://github.com/boltdb/bolt/blob/master/tx.go#L137).
- [x] Separate expiration queue and LRU item list.
- [x] Rename existing methods.
- [x] Remove `evictionreason_enumer.go` since it seems to add very little value yet creates quite a bit of unidiomatic code noise.
- [x] Clean up some of the code/add proper docs.
- [x] Add Loader interface and its helper types/funcs.
- [x] Improve mutex usage.
- [x] Make auto cleaner process optional. It should also be possible to stop and then restart it without closing the cache instance.
- [x] Remove `Close()`, replace it with `Start()` and `Stop()`
- [x] Remove error return values (most of them return only ErrClosed).
- [x] Add a method for manual expired item deletion.
- [x] Return/pass the whole `Item` type rather than its fields (applies to Get/Set/event functions).
- [x] Rewrite/improve tests.

I may have some more ideas later on.

What do you think @ReneKroon?

**Comment by swithek** [comment]
Do you mean leave the SimpleCache interface only as an example in the README? If so, I don't think that would give much value, since all the exported methods can be seen on the godoc page. Knowing those methods, it's not hard to design your own interface that contains only the methods you need (e.g. only Set and Purge).

**Comment by ReneKroon** [comment]
I do think it lowers the entry barrier for people looking 'just a cache with TTL' to seconds instead of having to study the docs.  I think it's an easy way to improve exposure of the library.

**Comment by swithek** [comment]
Sooner or later one would have to study the docs to know how to properly use the library. However, having a few good examples that show the basic and advanced usage, like now, is useful. I'm not suggesting these examples should be removed, I just don't see how they can be better with an interface defined in them. If anything, having too much information like this increases the confusion (what if the user doesn't want to use an interface at all?) The examples should be simple and to the point: they should show the usage of the most important methods, not how they can be used with other language elements. After all, if one is using go, one should already know how methods and interfaces work.

What I am proposing we should have is a straightforward README file and code that is somewhat similar to bolt's: https://github.com/boltdb/bolt

**Comment by ReneKroon** [comment]
ok, the bolt example looks very good!

**Comment by swithek** [comment]
I also think we should have only one `Get` method that returns an exported `*Item`. This way we wouldn't have to create new `GetX` methods each time a new piece of data is needed (e.g. ttl -> `GetWithTTL`). How does that sound @ReneKroon?

**Comment by adam-p** [comment]
Regarding the `SimpleCache` question: As an outsider shopping around for caches and reading your README and godoc, I don't see what `SimpleCache` provides. I can see that `Cache` implements it. Am I also supposed to implement it if I wanted... something? A different backend? But then I'd just use a different cache.

Unless I'm missing something, I don't think it's useful. (If it's just intended as a tidy collection of the available methods, it's not needed.)

**Comment by swithek** [comment]
The v3 has been released: https://github.com/jellydator/ttlcache/releases/tag/v3.0.0

**Comment by jpmeijers** [comment]
Being forced to move away from the ReneKroon cache now. It's quite a hassle changing my code to work with this repo. I wish there was a SimpleCache.

**Comment by davseby** [comment]
> I know this change happened quite some time ago, but upgrading from v2 is there no longer a way to change the default TTL and capacity?

There is. When creating a cache you may specify additional options [WithTTL](https://github.com/jellydator/ttlcache/blob/v3/options.go#L44) and [WithCapacity](https://github.com/jellydator/ttlcache/blob/v3/options.go#L36) to override those values.
