### ISSUE TITLE
Migrating from ReneKroon

### ISSUE THREAD

**Issue by jpmeijers** [jellydator/ttlcache#77]
Coming from the ReneKroon version of this cache, I'm hitting a few issues:

* ~~Where is the documentation? Maybe add a link to it in the README?~~ Found it, just hidden. And the godoc isn't answering my questions either.
* Add an example how to Get without extending the TTL.
* Is it really necessary to start another goroutine for every cache?
* Get doesn't return an error anymore when the object can't be found in the cache.

**Comment by jpmeijers** [comment]
Also getting a lot of module errors since this repo was moved. Ex:
```
go: finding module for package github.com/ReneKroon/ttlcache/v2
go: found github.com/ReneKroon/ttlcache/v2 in github.com/ReneKroon/ttlcache/v2 v2.11.1
go: wsq-api/pkg/database/billingdb imports
        github.com/ReneKroon/ttlcache/v2: github.com/ReneKroon/ttlcache/v2@v2.11.1: parsing go.mod:
        module declares its path as: github.com/jellydator/ttlcache/v2
                but was required as: github.com/ReneKroon/ttlcache/v2
```

**Comment by swithek** [comment]
1. The v3/latest README file has a reference/docs badge that redirects to the godoc page.
2. You can use `WithDisableTouchOnHit()` ([doc](https://pkg.go.dev/github.com/jellydator/ttlcache/v3#WithDisableTouchOnHit)).
3. Unless you handle expired item deletion in some other way, you need to start a goroutine for this ([doc](https://pkg.go.dev/github.com/jellydator/ttlcache/v3#Cache.Start): `It blocks until Stop is called`).
4. `If the item is not found, a nil value is returned ` ([doc](https://pkg.go.dev/github.com/jellydator/ttlcache/v3#Cache.Get)).

**Comment by jpmeijers** [comment]
1. Got it
2. The docs you link to just show that a function with that name exists. It does not tell me how to use it. Maybe we need an example?
3. Why does this need to be different (more complex) than how it was with V2?
4. Great. This detail is a little hidden. And I'm not a fan of returning a `nil`. What if the value I stored in the cache was a `nil`? `err` like with V2 is better.
