### ISSUE TITLE
Enhancement Req - Add option to the cache to prevent updates when using Set()

### ISSUE THREAD

**Issue by patpicos** [jellydator/ttlcache#78]
Use case:
I use the cache to capture data i receive over UDP. In some cases, i have competing producers that will send the same information for a Key. I want the first message to win and be the one persisted in the cache and not have further messages overwrite.

Looking at the cache.set() function, it searches for an existing element and overwrites it.
https://github.com/jellydator/ttlcache/blob/master/cache.go#L134-L142

I would like a new option for the cache set on creation to prevent overwrites 

```go
cache := ttlcache.New[string, string](
		ttlcache.WithTTL[string, string](30 * time.Minute),
                ttlcache.WithoutOverwrite(),
	)

//Pseudo-code to show the expectation
cache.Set("first", "value1", ttlcache.DefaultTTL)
cache.Set("first", "value2", ttlcache.DefaultTTL)
cache.Set("first", "value3", ttlcache.DefaultTTL)

v:= cache.Get("first").Value()
assert.Equal(t, "value1",v)
```

**Comment by patpicos** [comment]
@swithek I PR'd against master. I assume master is tracking to `v3` (that's the version I'm using in my project)

**Comment by patpicos** [comment]
@ReneKroon is this a PR you could review?

**Comment by ReneKroon** [comment]
Currently on holiday, will check back in in August

Op wo 27 jul. 2022 03:07 schreef Patrick Picard ***@***.***>:

**Comment by patpicos** [comment]
closed PR and closing issue. Code remains on fork.
