### ISSUE TITLE
RFC - Expiry based on passed in function (option during cache creation)

### ISSUE THREAD

**Issue by patpicos** [jellydator/ttlcache#80]
This is a request for comments / brainstorming...

Currently, `ttlCache` expires items if:
- a TTL threshold is met
- cache size is met

Would it be too much of an expansion to have a more dynamic expiry to include a passed in function?

For example, the function could check the content of the item and return a `bool` of whether it should be expired.

This could be configured as an option during cache creation to pass the function. The checks could be done in `item.isExpiredUnsafe()`

A workaround would be to do this outside of the cache by regularly iterating the cache item and running the function on each item and issuing delete if the criteria is met. However, that expiry logic would be nice to offload to the cache.

**Comment by swithek** [comment]
How/when would this function be called?

The capacity and TTL checks are rather efficient, i.e., they aren't performed randomly and additional internal queues are used for that. As I see it, the only way this dynamic function could work is if the user provided some duration after which it would be called (or `DeleteExpired()` would be called by the user). But even then the cache would have to iterate over all the items as no internal queues could be used.

I don't see how this addition could benefit this library, however, I understand that sometimes items need to be dynamically deleted. I think the best way to achieve this would be by using a method that would allow the user to iterate over the items in the cache. We have an issue for that as well: #71

**Comment by patpicos** [comment]
for some reason, the eviction was being done through a timer/scheduled function..which means my idea would have had legs. looking back, it seems to clean itself on accesses.

I think it will be best to have an external cleaning component that accepts the cache as an input and iterate on schedule to clean it.
