### ISSUE TITLE
Mention DefaultTTL and NoTTL in Set() docs

### ISSUE THREAD

**Issue by snirye** [jellydator/ttlcache#96]
`Set(key K, value V, opts ...[Option])`
passing 0 as default is a bit confusing, and its also not documented

**Comment by swithek** [comment]
There's `ttlcache.NoTTL` for this. Though I agree, the `Set()` docs could probably mention it as one of the options.

**Comment by snirye** [comment]
Thanks for the quick response. 

You probably meant DefaultTTL.
But still, I think it not so natural to explicit mention this for using default behaviour, if it's possible to use same options mechanism that being used for the `New ` function
https://github.com/jellydator/ttlcache/blob/master/cache.go#L61
Like this:
`Set(key K, value V, opts ...SetOption) `

I would be happy to implement if it help

**Comment by swithek** [comment]
> You probably meant DefaultTTL.
I meant `NoTTL`, which is something you'd want to use if you don't want to set any TTL (that's what I gathered was your intention in the initial comment).

At the moment, there aren't any other SetOptions, so this change would be a bit premature.
